var dri = {
  key:'staList',
  data:[
      {
      id:0,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
    {
      id:1,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
    {
      id:2,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
    {
      id:3,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
    {
      id:4,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
    {
      id:5,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
  ]}
  module.exports = {
    pastData: dri
  }