var goods = {
  key:'allList',
  data:[
      {
      id:0,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },  
    {
      id:1,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar3.png',
      name: '活力团长',
      nickname:'🥈银牌团长',
      good:'【本地新鲜苹果，甜蜜来袭】来自我们美丽的本地果园，每一颗苹果都是大自然的杰作，享受充足的阳光和清新的空气，自然成熟，口感纯正。',
      price:'￥3.99',
      cate: "all",
      ccate:"fru",
      src1:"/images/1.jpg",
      src2:"/images/2.jpg",
      src3:"/images/3.jpg",
      isFous:false,
    },
    {
      id:2,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar2.png',
      name: '努力小团长',
      nickname:'🌱成长团长',
      good:'【匠心独运，面香四溢】【纯手工制作】每一根面条，都由经验丰富的师傅亲手揉捏、擀制，不含任何添加剂，保留了面粉最纯粹的味道。',
      price:'￥1.99',
      cate: "all",
      ccate:"sta",
      src1:"/images/10.jpg",
      src2:"/images/11.jpg",
      src3:"/images/12.jpg",
      isFous:false,
    },
    {
      id:3,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
      name: '亲切小团长',
      nickname:'🥉铜牌团长',
      good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
      price:'￥6.56',
      cate: "all",
      ccate:"dri",
      src1:"/images/7.jpg",
      src2:"/images/8.jpg",
      src3:"/images/9.jpg",
      isFous:false,
    },
  {
    id:4,
    image: 'https://tdesign.gtimg.com/mobile/demos/avatar5.png',
    name: '美丽团长',
    nickname:'🏅金牌团长',
    good:'【美食新体验，禛香香菇肥牛】探寻味蕾的全新境界，禛香香菇肥牛，一款集营养与美味于一身的创新美食，等你来品鉴！',
    price:'￥3.89',
    cate: "all",
    ccate:"sna",
    src1:"/images/13.jpg",
    src2:"/images/14.jpg",
    src3:"/images/15.jpg",
    isFous:true,
  },
  {
    id:5,
    image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
    name: '快乐老团长',
    nickname:'🏅金牌团长',
    good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
    price:'￥2.99',
    cate: "all",
    ccate:"veg",
    src1:"/images/4.jpg",
    src2:"/images/5.jpg",
    src3:"/images/6.jpg",
    isFous:true
  },  
  {
    id:6,
    image: 'https://tdesign.gtimg.com/mobile/demos/avatar3.png',
    name: '活力团长',
    nickname:'🥈银牌团长',
    good:'【本地新鲜苹果，甜蜜来袭】来自我们美丽的本地果园，每一颗苹果都是大自然的杰作，享受充足的阳光和清新的空气，自然成熟，口感纯正。',
    price:'￥3.99',
    cate: "all",
    ccate:"fru",
    src1:"/images/1.jpg",
    src2:"/images/2.jpg",
    src3:"/images/3.jpg",
    isFous:false
  },
  {
    id:7,
    image: 'https://tdesign.gtimg.com/mobile/demos/avatar2.png',
    name: '努力小团长',
    nickname:'🌱成长团长',
    good:'【匠心独运，面香四溢】【纯手工制作】每一根面条，都由经验丰富的师傅亲手揉捏、擀制，不含任何添加剂，保留了面粉最纯粹的味道。',
    price:'￥1.99',
    cate: "all",
    ccate:"sta",
    src1:"/images/10.jpg",
    src2:"/images/11.jpg",
    src3:"/images/12.jpg",
    isFous:false
  },
  {
    id:8,
    image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
    name: '亲切小团长',
    nickname:'🥉铜牌团长',
    good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
    price:'￥6.56',
    cate: "all",
    ccate:"dri",
    src1:"/images/7.jpg",
    src2:"/images/8.jpg",
    src3:"/images/9.jpg",
    isFous:false
  },
{
  id:9,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar5.png',
  name: '美丽团长',
  nickname:'🏅金牌团长',
  good:'【美食新体验，禛香香菇肥牛】探寻味蕾的全新境界，禛香香菇肥牛，一款集营养与美味于一身的创新美食，等你来品鉴！',
  price:'￥3.89',
  cate: "all",
  ccate:"sna",
  src1:"/images/13.jpg",
  src2:"/images/14.jpg",
  src3:"/images/15.jpg",
  isFous:true
},
{
  id:10,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
  name: '快乐老团长',
  nickname:'🏅金牌团长',
  good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
  price:'￥2.99',
  cate: "all",
  ccate:"veg",
  src1:"/images/4.jpg",
  src2:"/images/5.jpg",
  src3:"/images/6.jpg",
  isFous:true
},  
{
  id:11,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar3.png',
  name: '活力团长',
  nickname:'🥈银牌团长',
  good:'【本地新鲜苹果，甜蜜来袭】来自我们美丽的本地果园，每一颗苹果都是大自然的杰作，享受充足的阳光和清新的空气，自然成熟，口感纯正。',
  price:'￥3.99',
  cate: "all",
  ccate:"fru",
  src1:"/images/1.jpg",
  src2:"/images/2.jpg",
  src3:"/images/3.jpg",
  isFous:false
},
{
  id:12,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar2.png',
  name: '努力小团长',
  nickname:'🌱成长团长',
  good:'【匠心独运，面香四溢】【纯手工制作】每一根面条，都由经验丰富的师傅亲手揉捏、擀制，不含任何添加剂，保留了面粉最纯粹的味道。',
  price:'￥1.99',
  cate: "all",
  ccate:"sta",
  src1:"/images/10.jpg",
  src2:"/images/11.jpg",
  src3:"/images/12.jpg",
  isFous:false
},
{
  id:13,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
  name: '亲切小团长',
  nickname:'🥉铜牌团长',
  good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
  price:'￥6.56',
  cate: "all",
  ccate:"dri",
  src1:"/images/7.jpg",
  src2:"/images/8.jpg",
  src3:"/images/9.jpg",
  isFous:false
},
{
  id:14,
image: 'https://tdesign.gtimg.com/mobile/demos/avatar5.png',
name: '美丽团长',
nickname:'🏅金牌团长',
good:'【美食新体验，禛香香菇肥牛】探寻味蕾的全新境界，禛香香菇肥牛，一款集营养与美味于一身的创新美食，等你来品鉴！',
price:'￥3.89',
cate: "all",
ccate:"sna",
src1:"/images/13.jpg",
src2:"/images/14.jpg",
src3:"/images/15.jpg",
isFous:true
},
{
  id:15,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
  name: '快乐老团长',
  nickname:'🏅金牌团长',
  good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
  price:'￥2.99',
  cate: "all",
  ccate:"veg",
  src1:"/images/4.jpg",
  src2:"/images/5.jpg",
  src3:"/images/6.jpg",
  isFous:true
},  
{
  id:16,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar3.png',
  name: '活力团长',
  nickname:'🥈银牌团长',
  good:'【本地新鲜苹果，甜蜜来袭】来自我们美丽的本地果园，每一颗苹果都是大自然的杰作，享受充足的阳光和清新的空气，自然成熟，口感纯正。',
  price:'￥3.99',
  cate: "all",
  ccate:"fru",
  src1:"/images/1.jpg",
  src2:"/images/2.jpg",
  src3:"/images/3.jpg",
  isFous:false
},
{
  id:17,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar2.png',
  name: '努力小团长',
  nickname:'🌱成长团长',
  good:'【匠心独运，面香四溢】【纯手工制作】每一根面条，都由经验丰富的师傅亲手揉捏、擀制，不含任何添加剂，保留了面粉最纯粹的味道。',
  price:'￥1.99',
  cate: "all",
  ccate:"sta",
  src1:"/images/10.jpg",
  src2:"/images/11.jpg",
  src3:"/images/12.jpg",
  isFous:false
},
{
  id:18,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
  name: '亲切小团长',
  nickname:'🥉铜牌团长',
  good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
  price:'￥6.56',
  cate: "all",
  ccate:"dri",
  src1:"/images/7.jpg",
  src2:"/images/8.jpg",
  src3:"/images/9.jpg",
  isFous:false
},
{
  id:19,
image: 'https://tdesign.gtimg.com/mobile/demos/avatar5.png',
name: '美丽团长',
nickname:'🏅金牌团长',
good:'【美食新体验，禛香香菇肥牛】探寻味蕾的全新境界，禛香香菇肥牛，一款集营养与美味于一身的创新美食，等你来品鉴！',
price:'￥3.89',
cate: "all",
ccate:"sna",
src1:"/images/13.jpg",
src2:"/images/14.jpg",
src3:"/images/15.jpg",
isFous:true
},
{
  id:20,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
  name: '快乐老团长',
  nickname:'🏅金牌团长',
  good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
  price:'￥2.99',
  cate: "all",
  ccate:"veg",
  src1:"/images/4.jpg",
  src2:"/images/5.jpg",
  src3:"/images/6.jpg",
  isFous:true
},  
{
  id:21,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar3.png',
  name: '活力团长',
  nickname:'🥈银牌团长',
  good:'【本地新鲜苹果，甜蜜来袭】来自我们美丽的本地果园，每一颗苹果都是大自然的杰作，享受充足的阳光和清新的空气，自然成熟，口感纯正。',
  price:'￥3.99',
  cate: "all",
  ccate:"fru",
  src1:"/images/1.jpg",
  src2:"/images/2.jpg",
  src3:"/images/3.jpg",
  isFous:false
},
{
  id:22,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar2.png',
  name: '努力小团长',
  nickname:'🌱成长团长',
  good:'【匠心独运，面香四溢】【纯手工制作】每一根面条，都由经验丰富的师傅亲手揉捏、擀制，不含任何添加剂，保留了面粉最纯粹的味道。',
  price:'￥1.99',
  cate: "all",
  ccate:"sta",
  src1:"/images/10.jpg",
  src2:"/images/11.jpg",
  src3:"/images/12.jpg",
  isFous:false
},
{
  id:23,
  image: 'https://tdesign.gtimg.com/mobile/demos/avatar4.png',
  name: '亲切小团长',
  nickname:'🥉铜牌团长',
  good:'【畅爽每一刻，尽在可口可乐】无论是炎炎夏日的一口清凉，还是朋友聚会的欢乐时光，可口可乐总能带来无与伦比的畅爽体验。',
  price:'￥6.56',
  cate: "all",
  ccate:"dri",
  src1:"/images/7.jpg",
  src2:"/images/8.jpg",
  src3:"/images/9.jpg",
  isFous:false
},
{
  id:24,
image: 'https://tdesign.gtimg.com/mobile/demos/avatar5.png',
name: '美丽团长',
nickname:'🏅金牌团长',
good:'【美食新体验，禛香香菇肥牛】探寻味蕾的全新境界，禛香香菇肥牛，一款集营养与美味于一身的创新美食，等你来品鉴！',
price:'￥3.89',
cate: "all",
ccate:"sna",
src1:"/images/13.jpg",
src2:"/images/14.jpg",
src3:"/images/15.jpg",
isFous:true
},
]
}
module.exports = {
  pastData: goods
}
