var veg = {
  key:'vegList',
  data:[
      {
      id:0,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },
    {
      id:1,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },
    {
      id:2,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },
    {
      id:3,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },
    {
      id:4,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },
    {
      id:5,
      image: 'https://tdesign.gtimg.com/mobile/demos/avatar1.png',
      name: '快乐老团长',
      nickname:'🏅金牌团长',
      good:'【本地新鲜红萝卜，营养满分！】🌿来自大自然的馈赠，我们的本地红萝卜新鲜上市啦！色泽鲜艳，口感脆甜，每一根都是大自然的精华。',
      price:'￥2.99',
      cate: "all",
      ccate:"veg",
      src1:"/images/4.jpg",
      src2:"/images/5.jpg",
      src3:"/images/6.jpg",
      isFous:true,
    },
  ]}
  module.exports = {
    pastData: veg
  }